/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Getnumber, GetnumberInterface } from "../Getnumber";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newNumber",
        type: "uint256",
      },
    ],
    name: "changeNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061016d806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806307391dd61461003b578063f2c9ecd81461006b575b600080fd5b610055600480360381019061005091906100e0565b610089565b604051610062919061011c565b60405180910390f35b61007361009c565b604051610080919061011c565b60405180910390f35b6000816000819055506000549050919050565b60008054905090565b600080fd5b6000819050919050565b6100bd816100aa565b81146100c857600080fd5b50565b6000813590506100da816100b4565b92915050565b6000602082840312156100f6576100f56100a5565b5b6000610104848285016100cb565b91505092915050565b610116816100aa565b82525050565b6000602082019050610131600083018461010d565b9291505056fea2646970667358221220cf987f1ab9788262b66a1c165a1d300222855614b56d73e8fc127dcf9097729064736f6c63430008120033";

type GetnumberConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GetnumberConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Getnumber__factory extends ContractFactory {
  constructor(...args: GetnumberConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Getnumber> {
    return super.deploy(overrides || {}) as Promise<Getnumber>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Getnumber {
    return super.attach(address) as Getnumber;
  }
  override connect(signer: Signer): Getnumber__factory {
    return super.connect(signer) as Getnumber__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GetnumberInterface {
    return new utils.Interface(_abi) as GetnumberInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Getnumber {
    return new Contract(address, _abi, signerOrProvider) as Getnumber;
  }
}
